# Generated by Django 4.2.6 on 2023-10-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_booking', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
