# Generated by Django 4.2.6 on 2023-10-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_booking', '0005_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
    ]
